### ISSUE TITLE
Build fails on linux 5.0rc8

### ISSUE THREAD

**Issue by muhviehstah** [antonio-petricca/paragon-ufsd-ntfs-driver-porting#10]
[make.log](https://github.com/antonio-petricca/paragon-ufsd-ntfs-driver-porting/files/2911654/make.log)

**Comment by muhviehstah** [comment]
see my dkms make.log

**Comment by antonio-petricca** [comment]
Hi, I ported the driver on 5.0 RC too, but I am waiting for the final
release in order take care of any other change.

Please, add a watch to this project to be notified about the new release.

Regards,
Antonio

Il Mer 27 Feb 2019, 19:05 Timo Sarawinski <notifications@github.com> ha
scritto:

**Comment by antonio-petricca** [comment]
Hi, I have just released the porting for 5.0.

**Comment by antonio-petricca** [comment]
Please, star this project if you wish. :+1:

**Comment by antonio-petricca** [comment]
Hi, I would inform you that I have just released a second hotfix.
