### ISSUE TITLE
KDE mounting driver

### ISSUE THREAD

**Issue by AdrianBan** [antonio-petricca/paragon-ufsd-ntfs-driver-porting#4]
Hi,

I've tested your patched version of driver and is working fine if I'm manually mounting the driver.
My issue is that if I have an external disk with NTFS and I want to mount it under KDE Dolphin I'm getting this error in dmesg:

`[  112.592026] ------------[ cut here ]------------
[  112.592028] request_module fs-ntfs succeeded, but still no fs?
[  112.592036] WARNING: CPU: 6 PID: 4674 at /build/linux-s3QDK1/linux-4.18.10/fs/filesystems.c:270 get_fs_type+0xd1/0xe0
[  112.592037] Modules linked in: sr_mod cdrom rfcomm twofish_generic twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common serpent_avx2 serpent_avx_x86_64 serpent_sse2_x86_64 serpent_generic blowfish_generic blowfish_x86_64 blowfish_common cast5_avx_x86_64 cast5_generic cast_common des_generic cbc algif_skcipher camellia_generic camellia_aesni_avx2 camellia_aesni_avx_x86_64 camellia_x86_64 xcbc sha512_ssse3 sha512_generic md4 algif_hash af_alg vmnet(O) xfrm_user xfrm4_tunnel tunnel4 ipcomp xfrm_ipcomp esp4 ah4 af_key xfrm_algo fuse vmw_vsock_vmci_transport vsock vmw_vmci l2tp_ppp l2tp_netlink l2tp_core vmmon(O) ip6_udp_tunnel udp_tunnel pppox ppp_generic slhc msr ctr ccm cmac bnep cpufreq_conservative cpufreq_powersave cpufreq_userspace binfmt_misc nls_ascii nls_cp437 vfat fat intel_rapl
[  112.592065]  ath3k x86_pkg_temp_thermal btusb intel_powerclamp arc4 btrtl btbcm btintel coretemp snd_hda_codec_hdmi snd_hda_codec_realtek ath9k bluetooth kvm_intel snd_hda_codec_generic ath9k_common kvm jitterentropy_rng irqbypass ath9k_hw crct10dif_pclmul crc32_pclmul ath snd_hda_intel uvcvideo ghash_clmulni_intel drbg snd_hda_codec videobuf2_vmalloc intel_cstate videobuf2_memops mac80211 snd_hda_core intel_uncore videobuf2_v4l2 ansi_cprng asus_nb_wmi videobuf2_common snd_hwdep intel_rapl_perf efi_pstore videodev snd_pcm iTCO_wdt asus_wmi sparse_keymap mei_me media snd_timer cfg80211 joydev serio_raw sg efivars pcspkr ecdh_generic rtsx_pci_ms snd iTCO_vendor_support memstick rfkill mei soundcore ie31200_edac ac evdev battery asus_wireless pcc_cpufreq vhba(O) i2c_smbus bbswitch(O) parport_pc ppdev
[  112.592096]  lp parport efivarfs ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 fscrypto ecb btrfs zstd_decompress zstd_compress xxhash raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c crc32c_generic raid1 raid0 multipath linear md_mod hid_logitech_hidpp hid_logitech_dj hid_generic usbhid hid sd_mod rtsx_pci_sdmmc crc32c_intel mmc_core mxm_wmi i915 ahci i2c_algo_bit libahci xhci_pci aesni_intel ehci_pci aes_x86_64 crypto_simd libata drm_kms_helper cryptd glue_helper xhci_hcd ehci_hcd rtsx_pci psmouse i2c_i801 scsi_mod lpc_ich r8169 mii usbcore drm usb_common thermal wmi video button
[  112.592128] CPU: 6 PID: 4674 Comm: pool Tainted: G           O      4.18.0-2-amd64 #1 Debian 4.18.10-2
[  112.592129] Hardware name: ASUSTeK COMPUTER INC. G56JK/G56JK, BIOS G56JK.202 09/26/2014
[  112.592131] RIP: 0010:get_fs_type+0xd1/0xe0
[  112.592131] Code: 31 c0 eb d3 80 3d d9 0d e8 00 00 75 c8 48 89 da 44 89 e6 48 c7 c7 48 6a 05 a5 48 89 04 24 c6 05 bf 0d e8 00 01 e8 7f 46 e0 ff <0f> 0b 48 8b 04 24 e9 62 ff ff ff 0f 1f 40 00 0f 1f 44 00 00 48 8b 
[  112.592150] RSP: 0018:ffffb5da08227e58 EFLAGS: 00010286
[  112.592151] RAX: 0000000000000000 RBX: ffff91ef5331bf60 RCX: 0000000000000006
[  112.592152] RDX: 0000000000000007 RSI: 0000000000000096 RDI: ffff91ef6ef96730
[  112.592152] RBP: 0000000000000000 R08: 000000000000042a R09: 0000000000000004
[  112.592153] R10: ffffb5da08227e80 R11: 0000000000000001 R12: 0000000000000004
[  112.592154] R13: ffff91eee8adc160 R14: ffff91ef5331bf60 R15: 0000000000000023
[  112.592155] FS:  00007f44dca0c700(0000) GS:ffff91ef6ef80000(0000) knlGS:0000000000000000
[  112.592155] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  112.592156] CR2: 00007fa65806c000 CR3: 0000000417358002 CR4: 00000000001606e0
[  112.592157] Call Trace:
[  112.592161]  do_mount+0x5c0/0xc70
[  112.592164]  ? _cond_resched+0x15/0x40
[  112.592169]  ? kmem_cache_alloc_trace+0x15d/0x1c0
[  112.592171]  ? copy_mount_options+0x28/0x220
[  112.592173]  ksys_mount+0x80/0xd0
[  112.592175]  __x64_sys_mount+0x21/0x30
[  112.592178]  do_syscall_64+0x55/0x110
[  112.592180]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  112.592183] RIP: 0033:0x7f44de7a8a1a
[  112.592183] Code: 48 8b 0d 71 e4 0b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 49 89 ca b8 a5 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 3e e4 0b 00 f7 d8 64 89 01 48 
[  112.592212] RSP: 002b:00007f44dca0b2d8 EFLAGS: 00000206 ORIG_RAX: 00000000000000a5
[  112.592214] RAX: ffffffffffffffda RBX: 00007f44d000aa00 RCX: 00007f44de7a8a1a
[  112.592215] RDX: 00007f44d0003750 RSI: 00007f44d00141f0 RDI: 00007f44d0003770
[  112.592216] RBP: 00007f44def2bf04 R08: 00007f44d006e5f0 R09: 0000000000000000
[  112.592216] R10: 00000000c0ed0006 R11: 0000000000000206 R12: 0000000000000000
[  112.592217] R13: 00000000c0ed0006 R14: 00007f44d0003770 R15: 00007f44d0003750
[  112.592219] ---[ end trace 9c03ff73828141e9 ]---
`
There is a solution to force the detection of NTFS filesystem to load UFSD driver instead?
I looked over internet for a solution but without success.

Kind regards,
Adrian

**Comment by AdrianBan** [comment]
Hi,

For others which will face the same issue I've found a solution.
The workaround is to create a script (mount helper) which will do the trick to mount the driver with -t ufsd instead -t ntfs.
Here is the code:

/sbin/mount.ntfs
`#!/bin/bash

disk=$1
shift
dstdir=$1
shift
#echo $@
opt=$@
mount $disk $dstdir $opt -t ufsd
`

**Comment by antonio-petricca** [comment]
Very good. :wink:
