### ISSUE TITLE
Raspberry pi - Unknown version of readdir

### ISSUE THREAD

**Issue by jperon** [antonio-petricca/paragon-ufsd-ntfs-driver-porting#5]
First let me thank you for this port !
I get this error when running `./configure` on a Raspbian : 

```sh
checking readdir... Unknown
configure: error: Unknown version of readdir
```

Here is the kernel version : `4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux`

**Comment by antonio-petricca** [comment]
Hi @jperon , despite of your compiling error, I would supply you an excerpt of the [Paragon website](https://www.paragon-software.com/home/ntfs-linux-professional/#features):

> This product supports x86 and x86-64 architectures.
Paragon Software Group also offers drivers for other architectures where Linux can be used. For example:
ARM
MIPS
SuperH (SH4)
Ubicom32
Power PC
For more information, please send us a request.

The UFSD driver is composed of two parts:

1. The Linux kernel module (which I tried to port on newer kernels).
2. A proprietary commercial component library included into the sources bundle.

The commercial library is available only for the x86-x86 platform, so you cannot recompile it on Rasperry Pi (ARM cpu).

Regards,
Antonio

**Comment by jperon** [comment]
Many thanks for the explanation !
