### ISSUE TITLE
Make error on Arch Linux with 4.19.23 LTS / 4.20.10 kernel

### ISSUE THREAD

**Issue by Drommer** [antonio-petricca/paragon-ufsd-ntfs-driver-porting#9]
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)

P.S. On Debian Sid with 4.19.0-3 kernel same problem.

P.S.2 Where is 'jnl' module file's in last version?

**Comment by antonio-petricca** [comment]
Hi, as I wrote in the README.md, I did not write the driver itself, but I have made many adjustments to compile it on latest kernels (not supported by Paragon).

The issue you addressed is related to the original driver code, so in order to fix it, I have to install your same distribution and try it, but unfortunately I have no time at this time.

Feel free, if you can, to find a solution on yourself, then post a pull request to contribute to this project.

Regards,
Antonio

**Comment by antonio-petricca** [comment]
On Arch 4.20.10 I got this error:

> In file included from...//ifslinux/ufsdvfs.c:115:
> ...//ifslinux/config.h:95:5: error: "HAVE_UAPI_LINUX_MOUNT_H" is not defined, evaluates to 0 [-Werror=undef]
>  #if HAVE_UAPI_LINUX_MOUNT_H

Is it the same?

**Comment by Drommer** [comment]
I check it on openSUSE Tumbleweed and have same result. This is strange. There are any dependencies other than the compiler, dkms and kernel source code?

My 'make driver' out:

> make[1]: вход в каталог «/usr/lib/modules/4.20.10-arch1-1-ARCH/build»
> make -C /lib/modules/4.20.10-arch1-1-ARCH/build KBUILD_SRC=/usr/lib/modules/4.20.10-arch1-1-ARCH/build \
> -f /usr/lib/modules/4.20.10-arch1-1-ARCH/build/Makefile modules
> make[2]: вход в каталог «/usr/lib/modules/4.20.10-arch1-1-ARCH/build»
> test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
> echo >&2;                                                       \
> echo >&2 "  ERROR: Kernel configuration is invalid.";           \
> echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
> echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
> echo >&2 ;                                                      \
> /bin/false)
> mkdir -p /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/.tmp_versions ; rm -f /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/.tmp_versions/*
> make -f /usr/lib/modules/4.20.10-arch1-1-ARCH/build/scripts/Makefile.build obj=/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources
>   gcc -Wp,-MD,/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/.crc32_calc.d -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89   -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/crc32_calc /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources//ifslinux/crc32_calc.c   
> Calculated hash of Kernel .config: 0xb81d5c02
> (cat /dev/null;   echo kernel//home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.ko;) > /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/modules.order
>   gcc -Wp,-MD,/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/.ufsdvfs.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include -I./arch/x86/include/generated  -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include -I./include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/uapi -I./include/generated/uapi -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/kconfig.h -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/compiler_types.h  -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=/usr/lib/modules/4.20.10-arch1-1-ARCH/build/= -Wno-packed-not-aligned -include /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/fs_conf.h -DUFSD_DEVICE=ufsd -DUFSD_USE_ASM_DIV64 -DNDEBUG -g0 -include drv_config.h -Wall -Werror -Wno-unknown-pragmas -Wno-date-time -include /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/hash_val.h  -DMODULE  -DKBUILD_BASENAME='"ufsdvfs"' -DKBUILD_MODNAME='"ufsd"' -c -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/ufsdvfs.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources//ifslinux/ufsdvfs.c
> /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources//ifslinux/ufsdvfs.c:129:9: замечание: #pragma message: PAGE_SHIFT=12
>  #pragma message "PAGE_SHIFT=" __stringify(PAGE_SHIFT)
>          ^~~~~~~
> /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources//ifslinux/ufsdvfs.c:130:9: замечание: #pragma message: THREAD_SIZE=(((1UL) << 12) << (2 + 0))
>  #pragma message "THREAD_SIZE=" __stringify(THREAD_SIZE)
>          ^~~~~~~
>    ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/ufsdvfs.o";
>   gcc -Wp,-MD,/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/.vfsdebug.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include -I./arch/x86/include/generated  -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include -I./include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/uapi -I./include/generated/uapi -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/kconfig.h -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/compiler_types.h  -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=/usr/lib/modules/4.20.10-arch1-1-ARCH/build/= -Wno-packed-not-aligned -include /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/fs_conf.h -DUFSD_DEVICE=ufsd -DUFSD_USE_ASM_DIV64 -DNDEBUG -g0 -include drv_config.h -Wall -Werror -Wno-unknown-pragmas -Wno-date-time  -DMODULE  -DKBUILD_BASENAME='"vfsdebug"' -DKBUILD_MODNAME='"ufsd"' -c -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/vfsdebug.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources//ifslinux/vfsdebug.c
>    ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/vfsdebug.o";
>   gcc -Wp,-MD,/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/.config_check.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include -I./arch/x86/include/generated  -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include -I./include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/uapi -I./include/generated/uapi -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/kconfig.h -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/compiler_types.h  -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=/usr/lib/modules/4.20.10-arch1-1-ARCH/build/= -Wno-packed-not-aligned -include /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/fs_conf.h -DUFSD_DEVICE=ufsd -DUFSD_USE_ASM_DIV64 -DNDEBUG -g0 -include drv_config.h -Wall -Werror -Wno-unknown-pragmas -Wno-date-time -include /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/hash_val.h  -DMODULE  -DKBUILD_BASENAME='"config_check"' -DKBUILD_MODNAME='"ufsd"' -c -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/config_check.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources//ifslinux/config_check.c
>    ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/config_check.o";
>   ld -m elf_x86_64  -z max-page-size=0x200000 -s -O2 -d -X    -r -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/ufsdvfs.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/vfsdebug.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/config_check.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/libufsd.o 
> make -f /usr/lib/modules/4.20.10-arch1-1-ARCH/build/scripts/Makefile.modpost
>   find /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/.tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost  -a -i ./Module.symvers -I /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/Module.symvers  -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/Module.symvers -S  -w  -s -T -
> WARNING: could not find /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/.libufsd.o.cmd for /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/libufsd.o
>   gcc -Wp,-MD,/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/.ufsd.mod.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include -I./arch/x86/include/generated  -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include -I./include -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/uapi -I./include/generated/uapi -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/kconfig.h -include /usr/lib/modules/4.20.10-arch1-1-ARCH/build/include/linux/compiler_types.h  -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ -I/home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=/usr/lib/modules/4.20.10-arch1-1-ARCH/build/= -Wno-packed-not-aligned -include /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ifslinux/fs_conf.h -DUFSD_DEVICE=ufsd -DUFSD_USE_ASM_DIV64 -DNDEBUG -g0 -include drv_config.h -Wall -Werror -Wno-unknown-pragmas -Wno-date-time  -DKBUILD_BASENAME='"ufsd.mod"' -DKBUILD_MODNAME='"ufsd"' -DMODULE  -c -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.mod.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.mod.c
>   ld -r -m elf_x86_64  -z max-page-size=0x200000 -s -O2 -d -X -T /usr/lib/modules/4.20.10-arch1-1-ARCH/build/scripts/module-common.lds  --build-id  -o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.ko /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.o /home/drommer/Downloads/paragon-ufsd-ntfs-driver-porting-master/sources/ufsd.mod.o ;  true
> make[2]: выход из каталога «/usr/lib/modules/4.20.10-arch1-1-ARCH/build»
> make[1]: выход из каталога «/usr/lib/modules/4.20.10-arch1-1-ARCH/build»
> /sbin/objcopy --only-keep-debug ufsd.ko ufsd.ko.dbg
> /sbin/strip -g --strip-unneeded ufsd.ko
> /sbin/strip -g --strip-unneeded ufsd.ko

**Comment by antonio-petricca** [comment]
> On Arch 4.20.10 I got this error:
> 
> > In file included from...//ifslinux/ufsdvfs.c:115:
> > ...//ifslinux/config.h:95:5: error: "HAVE_UAPI_LINUX_MOUNT_H" is not defined, evaluates to 0 [-Werror=undef]
> > #if HAVE_UAPI_LINUX_MOUNT_H
> 
> Is it the same?

Cleaning by `make clean` it worked, my build environment was dirty!

> I check it on openSUSE Tumbleweed and have same result. This is strange. There are any dependencies other than the compiler, dkms and kernel source code?
> 
> My 'make driver' out:

By your complete log I can see that message is a well known **warning**, you can ignore it!

> /sbin/strip -g --strip-unneeded ufsd.ko
> /sbin/strip -g --strip-unneeded ufsd.ko

The log last two lines state that the driver has been built successfully.

Try it by `sudo make driver_install` and report here the result...

**Comment by Drommer** [comment]
Yes, you are right, the driver works. Sorry.

**Comment by antonio-petricca** [comment]
No problem!
